### PR TITLE
Update the repo templates

### PR DESCRIPTION
**Pull request by renatho**
### Changes proposed in this Pull Request

* Standardize the repo templates based on these changes:
  * https://github.com/woocommerce/sensei-share-your-grade/pull/39
  * https://github.com/woocommerce/sensei-share-your-grade/pull/40

### CODE REVIEW

**Comment by gkaragia** [comment]
Hey @renatho should we merge this?

**Comment by renatho** [comment]
> Hey @renatho should we merge this?

Just to confirm, @donnapep, is in your queue to check these PRs about the repo templates?

**Comment by donnapep** [comment]
Please see https://github.com/woocommerce/sensei-media-attachments/pull/72/files#r400341840. We should take those out of all templates.

**Comment by renatho** [comment]
> Please see https://github.com/woocommerce/sensei-media-attachments/pull/72/files#r400341840. We should take those out of all templates.

Cool! Thank you for review, @donnapep! All repos updated. =) https://github.com/woocommerce/sensei-content-drip/pull/190/commits/23d2b5748aa0e107dc382d8f5cb87f8fcc005906

**Pull request merged**
