### PR TITLE
Check for Sensei using class name as well as folder name

### LINKED ISSUE #125: Don't rely on folder name to check if Sensei is active
Same issue as Certificates used to have:
https://github.com/woocommerce/sensei-certificates/issues/83

If the folder name for Sensei is not `woothemes-sensei` or `sensei` it will fail the `sensei_active_check` and Content Drip will not work.

### PR DESCRIPTION
**Pull request by danjjohnson**
Fixes #125

### CODE REVIEW

**Comment by mattyza** [comment]
@danjjohnson - Stumbled upon this during daily GitHub triage.

Perhaps the class checks should come first? I know some conditional flows in PHP drop out of the conditional as soon as one of the conditions isn't met. If the classes exist, are the folder name checks even necessary?

If the folder checks are important, it could also be worth checking for `sensei/woothemes-sensei.php` as a fallback to a common scenario we probably see users do.

**Comment by danjjohnson** [comment]
Thanks @mattyza 

@pgk I copied this from your [Certificates fix](https://github.com/woocommerce/sensei-certificates/commit/b4b115213dbeb920a40b8b2b09b8230c896f523d) :P 

Would you mind updating these with Matty's suggestions?

**Comment by alexsanford** [comment]
> Perhaps the class checks should come first? I know some conditional flows in PHP drop out of the conditional as soon as one of the conditions isn't met. If the classes exist, are the folder name checks even necessary?

There are tradeoffs. This looks like a problem for which there is no "Right Way" to do it :)

I feel like checking for the class or function is the "safer" way to do it, because then it doesn't matter what folder the user puts it in. As long as the plugin is activated, we should find the class or function.

However, as explained [here](https://pippinsplugins.com/checking-dependent-plugin-active/), there is a caveat: the order in which the plugins are loaded makes a difference. To safely do a class or function check, we should really wrap it in a `plugins_loaded` hook.

@pgk I would like to get your opinion on this. Do you think that a class/function check inside `plugins_loaded` would be sufficient? Is there a good reason to check for the files instead?

Another idea: what about just checking for the `woothemes-sensei.php` file in `self::$active_plugins`, regardless of what directory it's in? So we would effectively do a regex check for `woothemes-sensei\.php$`. Might be a little slower, and I don't know that it's much better than the class check, but it's an option. Thoughts?

**Comment by pgk** [comment]
I am tending towards a -1 with removing the other checks and just checking for classes.

The class check thing is indeed the most reliable way to check sensei is loaded. But it might fail unless the check is called at/after `plugins_loaded` (and it [isn't](https://github.com/woocommerce/sensei-content-drip/blob/master/sensei-content-drip.php#L52) in content drip's case).

It is really a matter of what we want to check. The way I understand it, the method is checking sensei is active, not if it's loaded.

If we check for class existence only, we need to only call the function within a `plugins_loaded` or on `init`.

**Comment by alexsanford** [comment]
> The class check thing is indeed the most reliable way to check sensei is loaded. But it might fail unless the check is called at/after plugins_loaded (and it isn't in content drip's case).

But couldn't we change that?

I'm looking at the code inside the `if ( is_sensei_active() )` conditional, and it looks like it does 4 things:

1. Load the Sensei_Content_Drip class.
2. Initialize the singleton inside of the Sensei_Content_Drip class.
3. Register an activation hook.
4. Register a deactivation hook.

AFAICT, steps 3 and 4 don't need Sensei to be loaded or active.

Step 1 is only needed for step 2 to work.

And step 2 is [already called inside a `plugins_loaded` action](https://github.com/woocommerce/sensei-content-drip/blob/master/sensei-content-drip.php#L67).

So my proposal would be to move steps 3 and 4 outside of the conditional, and then move everything else into the `plugins_loaded` hook. Something like:

```php
        function Sensei_Content_Drip() {
                if ( is_sensei_active() ) {
                    require_once __DIR__ . '/includes/class-sensei-content-drip.php';
                    return Sensei_Content_Drip::instance( __FILE__, '1.0.8' );
                }
        }

        // load this plugin only after sensei becomes available globaly
        add_action( 'plugins_loaded', 'Sensei_Content_Drip' ) ;

        /**
        * Plugin Activation
        */
        register_activation_hook( __FILE__, 'sensei_content_drip_activation' );

        function sensei_content_drip_activation() {
                $hook = 'woo_scd_daily_cron_hook';

                if ( false !== wp_next_scheduled( $hook ) ) {
                        wp_clear_scheduled_hook( $hook );
                }

                wp_schedule_event( time(), 'daily', $hook );
        }


        /**
         * Plugin Deactivation
         */
        register_deactivation_hook( __FILE__, 'sensei_content_drip_deactivation' );

        function sensei_content_drip_deactivation() {
                $hook = 'woo_scd_daily_cron_hook';
                wp_clear_scheduled_hook( $hook );

        }
```

@pgk what do you think?

**Comment by pgk** [comment]
@alexsanford I would move the checks inside the `Sensei_Content_Drip` class and always call `::instance` on  the `Sensei_Content_Drip` function. Then do the check inside `woo_scd_daily_cron_hook` if not already checked.

**Comment by donnapep** [comment]
This doesn't work as is and needs updating as per the above discussion.

**Comment by alexsanford** [comment]
Closing in favour of #146

**Pull request closed without merging**
