### PR TITLE
Fix time formatting by storing dates as unix timestamps in DB.

### PR DESCRIPTION
**Pull request by bor0**
Fixes https://github.com/woocommerce/sensei-content-drip/issues/103.

### CODE REVIEW

**Comment by pgk** [comment]
@bor0 can you resolve the conflicts with `master`?

**Comment by bor0** [comment]
@pgk, done

**Comment by pgk** [comment]
Looks good!

**Comment by pgk** [comment]
@bor0 What happens when this is ran on an already stored datestring? Would we get valid output?

**Comment by bor0** [comment]
@pgk, yeah, there is an issue with that.
screen shot 2016-11-02 at 13 59 05

Do you want me to write an upgrade script to fix the DB entries?

**Comment by pgk** [comment]
Handling the "legacy" scenario in code sounds good, users might not be able to run a script on their server.

**Comment by bor0** [comment]
@pgk, nice catch. Thank you!

Here's the new PR: https://github.com/woocommerce/sensei-content-drip/pull/111/.

**Pull request merged**
